export const bibleBooks = [
  { name: "Gênesis", abbrev: "gn" },
  { name: "Êxodo", abbrev: "ex" },
  { name: "Levítico", abbrev: "lv" },
  { name: "Números", abbrev: "nm" },
  { name: "Deuteronômio", abbrev: "dt" },
  { name: "Josué", abbrev: "js" },
  { name: "Juízes", abbrev: "jz" },
  { name: "Rute", abbrev: "rt" },
  { name: "1º Samuel", abbrev: "1sm" },
  { name: "2º Samuel", abbrev: "2sm" },
  { name: "1º Reis", abbrev: "1rs" },
  { name: "2º Reis", abbrev: "2rs" },
  { name: "1º Crônicas", abbrev: "1cr" },
  { name: "2º Crônicas", abbrev: "2cr" },
  { name: "Esdras", abbrev: "ed" },
  { name: "Neemias", abbrev: "ne" },
  { name: "Ester", abbrev: "et" },
  { name: "Jó", abbrev: "job" },
  { name: "Salmos", abbrev: "sl" },
  { name: "Provérbios", abbrev: "pv" },
  { name: "Eclesiastes", abbrev: "ec" },
  { name: "Cânticos", abbrev: "ct" },
  { name: "Isaías", abbrev: "is" },
  { name: "Jeremias", abbrev: "jr" },
  { name: "Lamentações de Jeremias", abbrev: "lm" },
  { name: "Ezequiel", abbrev: "ez" },
  { name: "Daniel", abbrev: "dn" },
  { name: "Oséias", abbrev: "os" },
  { name: "Joel", abbrev: "jl" },
  { name: "Amós", abbrev: "am" },
  { name: "Obadias", abbrev: "ob" },
  { name: "Jonas", abbrev: "jn" },
  { name: "Miquéias", abbrev: "mq" },
  { name: "Naum", abbrev: "na" },
  { name: "Habacuque", abbrev: "hc" },
  { name: "Sofonias", abbrev: "sf" },
  { name: "Ageu", abbrev: "ag" },
  { name: "Zacarias", abbrev: "zc" },
  { name: "Malaquias", abbrev: "ml" },
  { name: "Mateus", abbrev: "mt" },
  { name: "Marcos", abbrev: "mc" },
  { name: "Lucas", abbrev: "lc" },
  { name: "João", abbrev: "jo" },
  { name: "Atos", abbrev: "at" },
  { name: "Romanos", abbrev: "rm" },
  { name: "1ª Coríntios", abbrev: "1co" },
  { name: "2ª Coríntios", abbrev: "2co" },
  { name: "Gálatas", abbrev: "gl" },
  { name: "Efésios", abbrev: "ef" },
  { name: "Filipenses", abbrev: "fp" },
  { name: "Colossenses", abbrev: "cl" },
  { name: "1ª Tessalonicenses", abbrev: "1ts" },
  { name: "2ª Tessalonicenses", abbrev: "2ts" },
  { name: "1ª Timóteo", abbrev: "1tm" },
  { name: "2ª Timóteo", abbrev: "2tm" },
  { name: "Tito", abbrev: "tt" },
  { name: "Filemom", abbrev: "fm" },
  { name: "Hebreus", abbrev: "hb" },
  { name: "Tiago", abbrev: "tg" },
  { name: "1ª Pedro", abbrev: "1pe" },
  { name: "2ª Pedro", abbrev: "2pe" },
  { name: "1ª João", abbrev: "1jo" },
  { name: "2ª João", abbrev: "2jo" },
  { name: "3ª João", abbrev: "3jo" },
  { name: "Judas", abbrev: "jd" },
  { name: "Apocalipse", abbrev: "ap" }
];